# Generated by Django 6.1.1 on 2026-10-07 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tki_id', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9._/-]+$', 'Use letters, numbers, dot, slash, underscore or hyphen only.')])),
                ('client_id', models.CharField(db_index=True, max_length=40)),
                ('opened_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('fiber', 'Fiber / LOS'), ('router', 'Router / Wi-Fi'), ('pppoe', 'PPPoE / Authentication'), ('slow', 'Slow Internet'), ('billing', 'Billing'), ('olt', 'OLT / ONU'), ('isp', 'ISP / Upstream'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('feedback_pending', 'Feedback pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=24)),
                ('isp_related', models.BooleanField(default=False)),
                ('complaint', models.TextField()),
                ('support_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('troubleshooting', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='portfolio.complaintticket')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
