# Generated by Django 6.1.1 on 2026-10-08 12:27

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    Ticket = apps.get_model("portfolio", "ComplaintTicket")
    Ticket.objects.filter(status__in=["resolved", "closed"]).update(status="solved")
    Ticket.objects.filter(status__in=["open", "assigned", "in_progress", "feedback_pending"]).update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintticket',
            name='attention',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='dependency',
            field=models.CharField(blank=True, choices=[('technician', 'Technician'), ('isp', 'ISP'), ('support_engineer', 'Support Engineer'), ('noc_engineer', 'NOC Engineer'), ('customer', 'Customer'), ('manor_other_team', 'Manor Other Team')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='field_support_engineer',
            field=models.CharField(blank=True, choices=[('abir', 'Abir'), ('faruk', 'Faruk'), ('prodosh', 'Prodosh'), ('rukunuzzaman', 'Rukunuzzaman')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='higher_level_noc',
            field=models.CharField(blank=True, choices=[('farzana', 'Farzana'), ('hasan', 'Hasan'), ('jewel', 'Jewel'), ('riaz', 'Riaz')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='remarks',
            field=models.TextField(blank=True, help_text='Latest/last operational comment'),
        ),
        migrations.AlterField(
            model_name='complaintticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24),
        ),
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
    ]
