# Generated by Django 6.1.1 on 2026-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_seed_initial_tki_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintticket',
            name='field_support_done',
            field=models.BooleanField(db_index=True, default=False, help_text='Selected field engineer completed support'),
        ),
        migrations.AddField(
            model_name='complaintticket',
            name='noc_field_visit_done',
            field=models.BooleanField(db_index=True, default=False, help_text='Selected NOC engineer completed a field visit'),
        ),
    ]
